import{i as p,S as h}from"./assets/vendor-46aac873.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const g="https://pixabay.com/api/",$="key=41516646-ec27055f09ddd37d9bfda39a5",b="image_type=photo",S="orientation=horizontal",L="safesearch=true",q=document.querySelectorAll(".gallery.gallery-item");for(const r of q)console.log(r);const D=document.querySelector(".form"),k=document.querySelector(".gallery"),v=document.querySelector("body");D.addEventListener("submit",r=>{r.preventDefault(),w(),v.insertAdjacentHTML("beforeend",'<span class="loader"></span>');const o=r.target.elements.search.value;fetch(`${g}?${$}&q=${o}&${b}&${S}&${L}`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()}).then(s=>{const a=s.hits;a.length||p.error({message:"❌ Sorry, there are no images matching your search query. Please, try again!",icon:"",position:"topRight"});const e=a.reduce((l,{webformatURL:n,largeImageURL:i,tags:u,likes:d,views:y,comments:f,downloads:m})=>l+`<li class="gallery-item">
            <a class="gallery-link" href="${i}">
                <img class="gallery-image" src="${n}" alt="${u}"/>
            </a>
            <ul class="characteristics-list">
            <li class="characteristics"><span class="characteristics-titel">Likes</span> <span>${d}</span></li>
            <li class="characteristics"><span class="characteristics-titel">Views</span> <span>${y}</span></li>
            <li class="characteristics"><span class="characteristics-titel">Comments</span> <span>${f}</span></li>
            <li class="characteristics"><span class="characteristics-titel">Downloads</span> <span>${m}</span></li>
        </ul>
            
        </li>`,"");k.insertAdjacentHTML("beforeend",e),new h(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"}).refresh(),document.querySelector(".loader").remove()}).catch(s=>{console.log(s.message)})});function w(){const r=document.querySelectorAll(".gallery-item");for(const o of r)o.remove()}
//# sourceMappingURL=commonHelpers.js.map
